
package sri.web.template.models

import scala.scalajs.js
import scala.scalajs.js.annotation.{JSImport}

import scalajsplus.{
  OptDefault,
  OptionalParam
}
import scalajsplus.macros.FunctionObjectMacro


 /** this file is automatically generated on 2018-03-21T22:40:15.449Z

  don't modify this file directly */
object Source {
  val RELAY_URL: String = ""
}
 


trait CreateFile extends js.Object  {
  val name :String 
}

object CreateFile {

 def apply(name :String ):CreateFile = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[CreateFile]
 }

}

     



trait CreateFileInput extends js.Object  {
  val name :String 
val clientMutationId :String 
}

object CreateFileInput {

 def apply(name :String ,
clientMutationId :String ):CreateFileInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[CreateFileInput]
 }

}

     


@js.native
trait CreateFilePayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val file :js.UndefOr[File] = js.native
val edge :js.UndefOr[FileEdge] = js.native
}
     



trait CreatePost extends js.Object  {
  val description :String 
val imageUrl :String 
}

object CreatePost {

 def apply(description :String ,
imageUrl :String ):CreatePost = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[CreatePost]
 }

}

     



trait CreatePostInput extends js.Object  {
  val description :String 
val imageUrl :String 
val clientMutationId :String 
}

object CreatePostInput {

 def apply(description :String ,
imageUrl :String ,
clientMutationId :String ):CreatePostInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[CreatePostInput]
 }

}

     


@js.native
trait CreatePostPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val post :js.UndefOr[Post] = js.native
val edge :js.UndefOr[PostEdge] = js.native
}
     


@js.native
trait CreateUserPayload extends js.Object  {
  val user :js.UndefOr[User] = js.native
val clientMutationId :js.UndefOr[String] = js.native
val viewer :Viewer = js.native
}
     




trait DeleteFileInput extends js.Object  {
  val id :String 
val clientMutationId :String 
}

object DeleteFileInput {

 def apply(id :String ,
clientMutationId :String ):DeleteFileInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[DeleteFileInput]
 }

}

     


@js.native
trait DeleteFilePayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val file :js.UndefOr[File] = js.native
val edge :js.UndefOr[FileEdge] = js.native
val deletedId :js.UndefOr[String] = js.native
}
     



trait DeletePostInput extends js.Object  {
  val id :String 
val clientMutationId :String 
}

object DeletePostInput {

 def apply(id :String ,
clientMutationId :String ):DeletePostInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[DeletePostInput]
 }

}

     


@js.native
trait DeletePostPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val post :js.UndefOr[Post] = js.native
val edge :js.UndefOr[PostEdge] = js.native
val deletedId :js.UndefOr[String] = js.native
}
     



trait DeleteUserInput extends js.Object  {
  val id :String 
val clientMutationId :String 
}

object DeleteUserInput {

 def apply(id :String ,
clientMutationId :String ):DeleteUserInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[DeleteUserInput]
 }

}

     


@js.native
trait DeleteUserPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val user :js.UndefOr[User] = js.native
val edge :js.UndefOr[UserEdge] = js.native
val deletedId :js.UndefOr[String] = js.native
}
     


@js.native
trait File extends Node  {
  val contentType :String = js.native
val createdAt :String = js.native

val name :String = js.native
val secret :String = js.native
val size :Int = js.native
val updatedAt :String = js.native
val url :String = js.native
}
     


@js.native
trait FileConnection extends js.Object  {
  val pageInfo :PageInfo = js.native
val edges :js.Array[FileEdge] = js.native
val count :Int = js.native
}
     


@js.native
trait FileEdge extends js.Object  {
  val node :File = js.native
val cursor :String = js.native
}
     



trait FileFilter extends js.Object  {
  val AND :js.UndefOr[js.Array[FileFilter]]  = js.undefined
val OR :js.UndefOr[js.Array[FileFilter]]  = js.undefined
val contentType :js.UndefOr[String]  = js.undefined
val contentType_not :js.UndefOr[String]  = js.undefined
val contentType_in :js.UndefOr[js.Array[String]]  = js.undefined
val contentType_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val contentType_lt :js.UndefOr[String]  = js.undefined
val contentType_lte :js.UndefOr[String]  = js.undefined
val contentType_gt :js.UndefOr[String]  = js.undefined
val contentType_gte :js.UndefOr[String]  = js.undefined
val contentType_contains :js.UndefOr[String]  = js.undefined
val contentType_not_contains :js.UndefOr[String]  = js.undefined
val contentType_starts_with :js.UndefOr[String]  = js.undefined
val contentType_not_starts_with :js.UndefOr[String]  = js.undefined
val contentType_ends_with :js.UndefOr[String]  = js.undefined
val contentType_not_ends_with :js.UndefOr[String]  = js.undefined
val createdAt :js.UndefOr[String]  = js.undefined
val createdAt_not :js.UndefOr[String]  = js.undefined
val createdAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_lt :js.UndefOr[String]  = js.undefined
val createdAt_lte :js.UndefOr[String]  = js.undefined
val createdAt_gt :js.UndefOr[String]  = js.undefined
val createdAt_gte :js.UndefOr[String]  = js.undefined
val id :js.UndefOr[String]  = js.undefined
val id_not :js.UndefOr[String]  = js.undefined
val id_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_lt :js.UndefOr[String]  = js.undefined
val id_lte :js.UndefOr[String]  = js.undefined
val id_gt :js.UndefOr[String]  = js.undefined
val id_gte :js.UndefOr[String]  = js.undefined
val id_contains :js.UndefOr[String]  = js.undefined
val id_not_contains :js.UndefOr[String]  = js.undefined
val id_starts_with :js.UndefOr[String]  = js.undefined
val id_not_starts_with :js.UndefOr[String]  = js.undefined
val id_ends_with :js.UndefOr[String]  = js.undefined
val id_not_ends_with :js.UndefOr[String]  = js.undefined
val name :js.UndefOr[String]  = js.undefined
val name_not :js.UndefOr[String]  = js.undefined
val name_in :js.UndefOr[js.Array[String]]  = js.undefined
val name_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val name_lt :js.UndefOr[String]  = js.undefined
val name_lte :js.UndefOr[String]  = js.undefined
val name_gt :js.UndefOr[String]  = js.undefined
val name_gte :js.UndefOr[String]  = js.undefined
val name_contains :js.UndefOr[String]  = js.undefined
val name_not_contains :js.UndefOr[String]  = js.undefined
val name_starts_with :js.UndefOr[String]  = js.undefined
val name_not_starts_with :js.UndefOr[String]  = js.undefined
val name_ends_with :js.UndefOr[String]  = js.undefined
val name_not_ends_with :js.UndefOr[String]  = js.undefined
val secret :js.UndefOr[String]  = js.undefined
val secret_not :js.UndefOr[String]  = js.undefined
val secret_in :js.UndefOr[js.Array[String]]  = js.undefined
val secret_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val secret_lt :js.UndefOr[String]  = js.undefined
val secret_lte :js.UndefOr[String]  = js.undefined
val secret_gt :js.UndefOr[String]  = js.undefined
val secret_gte :js.UndefOr[String]  = js.undefined
val secret_contains :js.UndefOr[String]  = js.undefined
val secret_not_contains :js.UndefOr[String]  = js.undefined
val secret_starts_with :js.UndefOr[String]  = js.undefined
val secret_not_starts_with :js.UndefOr[String]  = js.undefined
val secret_ends_with :js.UndefOr[String]  = js.undefined
val secret_not_ends_with :js.UndefOr[String]  = js.undefined
val size :js.UndefOr[Int]  = js.undefined
val size_not :js.UndefOr[Int]  = js.undefined
val size_in :js.UndefOr[js.Array[Int]]  = js.undefined
val size_not_in :js.UndefOr[js.Array[Int]]  = js.undefined
val size_lt :js.UndefOr[Int]  = js.undefined
val size_lte :js.UndefOr[Int]  = js.undefined
val size_gt :js.UndefOr[Int]  = js.undefined
val size_gte :js.UndefOr[Int]  = js.undefined
val updatedAt :js.UndefOr[String]  = js.undefined
val updatedAt_not :js.UndefOr[String]  = js.undefined
val updatedAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_lt :js.UndefOr[String]  = js.undefined
val updatedAt_lte :js.UndefOr[String]  = js.undefined
val updatedAt_gt :js.UndefOr[String]  = js.undefined
val updatedAt_gte :js.UndefOr[String]  = js.undefined
val url :js.UndefOr[String]  = js.undefined
val url_not :js.UndefOr[String]  = js.undefined
val url_in :js.UndefOr[js.Array[String]]  = js.undefined
val url_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val url_lt :js.UndefOr[String]  = js.undefined
val url_lte :js.UndefOr[String]  = js.undefined
val url_gt :js.UndefOr[String]  = js.undefined
val url_gte :js.UndefOr[String]  = js.undefined
val url_contains :js.UndefOr[String]  = js.undefined
val url_not_contains :js.UndefOr[String]  = js.undefined
val url_starts_with :js.UndefOr[String]  = js.undefined
val url_not_starts_with :js.UndefOr[String]  = js.undefined
val url_ends_with :js.UndefOr[String]  = js.undefined
val url_not_ends_with :js.UndefOr[String]  = js.undefined
}

object FileFilter {

 def apply(AND :OptionalParam[js.Array[FileFilter]]  = OptDefault,
OR :OptionalParam[js.Array[FileFilter]]  = OptDefault,
contentType :OptionalParam[String]  = OptDefault,
contentType_not :OptionalParam[String]  = OptDefault,
contentType_in :OptionalParam[js.Array[String]]  = OptDefault,
contentType_not_in :OptionalParam[js.Array[String]]  = OptDefault,
contentType_lt :OptionalParam[String]  = OptDefault,
contentType_lte :OptionalParam[String]  = OptDefault,
contentType_gt :OptionalParam[String]  = OptDefault,
contentType_gte :OptionalParam[String]  = OptDefault,
contentType_contains :OptionalParam[String]  = OptDefault,
contentType_not_contains :OptionalParam[String]  = OptDefault,
contentType_starts_with :OptionalParam[String]  = OptDefault,
contentType_not_starts_with :OptionalParam[String]  = OptDefault,
contentType_ends_with :OptionalParam[String]  = OptDefault,
contentType_not_ends_with :OptionalParam[String]  = OptDefault,
createdAt :OptionalParam[String]  = OptDefault,
createdAt_not :OptionalParam[String]  = OptDefault,
createdAt_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_lt :OptionalParam[String]  = OptDefault,
createdAt_lte :OptionalParam[String]  = OptDefault,
createdAt_gt :OptionalParam[String]  = OptDefault,
createdAt_gte :OptionalParam[String]  = OptDefault,
id :OptionalParam[String]  = OptDefault,
id_not :OptionalParam[String]  = OptDefault,
id_in :OptionalParam[js.Array[String]]  = OptDefault,
id_not_in :OptionalParam[js.Array[String]]  = OptDefault,
id_lt :OptionalParam[String]  = OptDefault,
id_lte :OptionalParam[String]  = OptDefault,
id_gt :OptionalParam[String]  = OptDefault,
id_gte :OptionalParam[String]  = OptDefault,
id_contains :OptionalParam[String]  = OptDefault,
id_not_contains :OptionalParam[String]  = OptDefault,
id_starts_with :OptionalParam[String]  = OptDefault,
id_not_starts_with :OptionalParam[String]  = OptDefault,
id_ends_with :OptionalParam[String]  = OptDefault,
id_not_ends_with :OptionalParam[String]  = OptDefault,
name :OptionalParam[String]  = OptDefault,
name_not :OptionalParam[String]  = OptDefault,
name_in :OptionalParam[js.Array[String]]  = OptDefault,
name_not_in :OptionalParam[js.Array[String]]  = OptDefault,
name_lt :OptionalParam[String]  = OptDefault,
name_lte :OptionalParam[String]  = OptDefault,
name_gt :OptionalParam[String]  = OptDefault,
name_gte :OptionalParam[String]  = OptDefault,
name_contains :OptionalParam[String]  = OptDefault,
name_not_contains :OptionalParam[String]  = OptDefault,
name_starts_with :OptionalParam[String]  = OptDefault,
name_not_starts_with :OptionalParam[String]  = OptDefault,
name_ends_with :OptionalParam[String]  = OptDefault,
name_not_ends_with :OptionalParam[String]  = OptDefault,
secret :OptionalParam[String]  = OptDefault,
secret_not :OptionalParam[String]  = OptDefault,
secret_in :OptionalParam[js.Array[String]]  = OptDefault,
secret_not_in :OptionalParam[js.Array[String]]  = OptDefault,
secret_lt :OptionalParam[String]  = OptDefault,
secret_lte :OptionalParam[String]  = OptDefault,
secret_gt :OptionalParam[String]  = OptDefault,
secret_gte :OptionalParam[String]  = OptDefault,
secret_contains :OptionalParam[String]  = OptDefault,
secret_not_contains :OptionalParam[String]  = OptDefault,
secret_starts_with :OptionalParam[String]  = OptDefault,
secret_not_starts_with :OptionalParam[String]  = OptDefault,
secret_ends_with :OptionalParam[String]  = OptDefault,
secret_not_ends_with :OptionalParam[String]  = OptDefault,
size :OptionalParam[Int]  = OptDefault,
size_not :OptionalParam[Int]  = OptDefault,
size_in :OptionalParam[js.Array[Int]]  = OptDefault,
size_not_in :OptionalParam[js.Array[Int]]  = OptDefault,
size_lt :OptionalParam[Int]  = OptDefault,
size_lte :OptionalParam[Int]  = OptDefault,
size_gt :OptionalParam[Int]  = OptDefault,
size_gte :OptionalParam[Int]  = OptDefault,
updatedAt :OptionalParam[String]  = OptDefault,
updatedAt_not :OptionalParam[String]  = OptDefault,
updatedAt_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_lt :OptionalParam[String]  = OptDefault,
updatedAt_lte :OptionalParam[String]  = OptDefault,
updatedAt_gt :OptionalParam[String]  = OptDefault,
updatedAt_gte :OptionalParam[String]  = OptDefault,
url :OptionalParam[String]  = OptDefault,
url_not :OptionalParam[String]  = OptDefault,
url_in :OptionalParam[js.Array[String]]  = OptDefault,
url_not_in :OptionalParam[js.Array[String]]  = OptDefault,
url_lt :OptionalParam[String]  = OptDefault,
url_lte :OptionalParam[String]  = OptDefault,
url_gt :OptionalParam[String]  = OptDefault,
url_gte :OptionalParam[String]  = OptDefault,
url_contains :OptionalParam[String]  = OptDefault,
url_not_contains :OptionalParam[String]  = OptDefault,
url_starts_with :OptionalParam[String]  = OptDefault,
url_not_starts_with :OptionalParam[String]  = OptDefault,
url_ends_with :OptionalParam[String]  = OptDefault,
url_not_ends_with :OptionalParam[String]  = OptDefault):FileFilter = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[FileFilter]
 }

}

     


@js.native
trait FileOrderBy extends js.Object

object FileOrderBy {
  @inline def contentType_ASC = "contentType_ASC".asInstanceOf[FileOrderBy] 
@inline def contentType_DESC = "contentType_DESC".asInstanceOf[FileOrderBy] 
@inline def createdAt_ASC = "createdAt_ASC".asInstanceOf[FileOrderBy] 
@inline def createdAt_DESC = "createdAt_DESC".asInstanceOf[FileOrderBy] 
@inline def id_ASC = "id_ASC".asInstanceOf[FileOrderBy] 
@inline def id_DESC = "id_DESC".asInstanceOf[FileOrderBy] 
@inline def name_ASC = "name_ASC".asInstanceOf[FileOrderBy] 
@inline def name_DESC = "name_DESC".asInstanceOf[FileOrderBy] 
@inline def secret_ASC = "secret_ASC".asInstanceOf[FileOrderBy] 
@inline def secret_DESC = "secret_DESC".asInstanceOf[FileOrderBy] 
@inline def size_ASC = "size_ASC".asInstanceOf[FileOrderBy] 
@inline def size_DESC = "size_DESC".asInstanceOf[FileOrderBy] 
@inline def updatedAt_ASC = "updatedAt_ASC".asInstanceOf[FileOrderBy] 
@inline def updatedAt_DESC = "updatedAt_DESC".asInstanceOf[FileOrderBy] 
@inline def url_ASC = "url_ASC".asInstanceOf[FileOrderBy] 
@inline def url_DESC = "url_DESC".asInstanceOf[FileOrderBy] 
}

     


@js.native
trait Mutation extends js.Object  {
  val createFile :js.UndefOr[CreateFilePayload] = js.native
val createPost :js.UndefOr[CreatePostPayload] = js.native
val updateFile :js.UndefOr[UpdateFilePayload] = js.native
val updatePost :js.UndefOr[UpdatePostPayload] = js.native
val updateUser :js.UndefOr[UpdateUserPayload] = js.native
val updateOrCreateFile :js.UndefOr[UpdateOrCreateFilePayload] = js.native
val updateOrCreatePost :js.UndefOr[UpdateOrCreatePostPayload] = js.native
val updateOrCreateUser :js.UndefOr[UpdateOrCreateUserPayload] = js.native
val deleteFile :js.UndefOr[DeleteFilePayload] = js.native
val deletePost :js.UndefOr[DeletePostPayload] = js.native
val deleteUser :js.UndefOr[DeleteUserPayload] = js.native
val createUser :CreateUserPayload = js.native
}
     


@js.native
trait Node extends js.Object  {
  val id :String = js.native
}
     


@js.native
trait PageInfo extends js.Object  {
  val hasNextPage :Boolean = js.native
val hasPreviousPage :Boolean = js.native
val startCursor :js.UndefOr[String] = js.native
val endCursor :js.UndefOr[String] = js.native
}
     


@js.native
trait Post extends Node  {
  val createdAt :String = js.native
val description :String = js.native

val imageUrl :String = js.native
val updatedAt :String = js.native
}
     


@js.native
trait PostConnection extends js.Object  {
  val pageInfo :PageInfo = js.native
val edges :js.Array[PostEdge] = js.native
val count :Int = js.native
}
     


@js.native
trait PostEdge extends js.Object  {
  val node :Post = js.native
val cursor :String = js.native
}
     



trait PostFilter extends js.Object  {
  val AND :js.UndefOr[js.Array[PostFilter]]  = js.undefined
val OR :js.UndefOr[js.Array[PostFilter]]  = js.undefined
val createdAt :js.UndefOr[String]  = js.undefined
val createdAt_not :js.UndefOr[String]  = js.undefined
val createdAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_lt :js.UndefOr[String]  = js.undefined
val createdAt_lte :js.UndefOr[String]  = js.undefined
val createdAt_gt :js.UndefOr[String]  = js.undefined
val createdAt_gte :js.UndefOr[String]  = js.undefined
val description :js.UndefOr[String]  = js.undefined
val description_not :js.UndefOr[String]  = js.undefined
val description_in :js.UndefOr[js.Array[String]]  = js.undefined
val description_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val description_lt :js.UndefOr[String]  = js.undefined
val description_lte :js.UndefOr[String]  = js.undefined
val description_gt :js.UndefOr[String]  = js.undefined
val description_gte :js.UndefOr[String]  = js.undefined
val description_contains :js.UndefOr[String]  = js.undefined
val description_not_contains :js.UndefOr[String]  = js.undefined
val description_starts_with :js.UndefOr[String]  = js.undefined
val description_not_starts_with :js.UndefOr[String]  = js.undefined
val description_ends_with :js.UndefOr[String]  = js.undefined
val description_not_ends_with :js.UndefOr[String]  = js.undefined
val id :js.UndefOr[String]  = js.undefined
val id_not :js.UndefOr[String]  = js.undefined
val id_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_lt :js.UndefOr[String]  = js.undefined
val id_lte :js.UndefOr[String]  = js.undefined
val id_gt :js.UndefOr[String]  = js.undefined
val id_gte :js.UndefOr[String]  = js.undefined
val id_contains :js.UndefOr[String]  = js.undefined
val id_not_contains :js.UndefOr[String]  = js.undefined
val id_starts_with :js.UndefOr[String]  = js.undefined
val id_not_starts_with :js.UndefOr[String]  = js.undefined
val id_ends_with :js.UndefOr[String]  = js.undefined
val id_not_ends_with :js.UndefOr[String]  = js.undefined
val imageUrl :js.UndefOr[String]  = js.undefined
val imageUrl_not :js.UndefOr[String]  = js.undefined
val imageUrl_in :js.UndefOr[js.Array[String]]  = js.undefined
val imageUrl_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val imageUrl_lt :js.UndefOr[String]  = js.undefined
val imageUrl_lte :js.UndefOr[String]  = js.undefined
val imageUrl_gt :js.UndefOr[String]  = js.undefined
val imageUrl_gte :js.UndefOr[String]  = js.undefined
val imageUrl_contains :js.UndefOr[String]  = js.undefined
val imageUrl_not_contains :js.UndefOr[String]  = js.undefined
val imageUrl_starts_with :js.UndefOr[String]  = js.undefined
val imageUrl_not_starts_with :js.UndefOr[String]  = js.undefined
val imageUrl_ends_with :js.UndefOr[String]  = js.undefined
val imageUrl_not_ends_with :js.UndefOr[String]  = js.undefined
val updatedAt :js.UndefOr[String]  = js.undefined
val updatedAt_not :js.UndefOr[String]  = js.undefined
val updatedAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_lt :js.UndefOr[String]  = js.undefined
val updatedAt_lte :js.UndefOr[String]  = js.undefined
val updatedAt_gt :js.UndefOr[String]  = js.undefined
val updatedAt_gte :js.UndefOr[String]  = js.undefined
}

object PostFilter {

 def apply(AND :OptionalParam[js.Array[PostFilter]]  = OptDefault,
OR :OptionalParam[js.Array[PostFilter]]  = OptDefault,
createdAt :OptionalParam[String]  = OptDefault,
createdAt_not :OptionalParam[String]  = OptDefault,
createdAt_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_lt :OptionalParam[String]  = OptDefault,
createdAt_lte :OptionalParam[String]  = OptDefault,
createdAt_gt :OptionalParam[String]  = OptDefault,
createdAt_gte :OptionalParam[String]  = OptDefault,
description :OptionalParam[String]  = OptDefault,
description_not :OptionalParam[String]  = OptDefault,
description_in :OptionalParam[js.Array[String]]  = OptDefault,
description_not_in :OptionalParam[js.Array[String]]  = OptDefault,
description_lt :OptionalParam[String]  = OptDefault,
description_lte :OptionalParam[String]  = OptDefault,
description_gt :OptionalParam[String]  = OptDefault,
description_gte :OptionalParam[String]  = OptDefault,
description_contains :OptionalParam[String]  = OptDefault,
description_not_contains :OptionalParam[String]  = OptDefault,
description_starts_with :OptionalParam[String]  = OptDefault,
description_not_starts_with :OptionalParam[String]  = OptDefault,
description_ends_with :OptionalParam[String]  = OptDefault,
description_not_ends_with :OptionalParam[String]  = OptDefault,
id :OptionalParam[String]  = OptDefault,
id_not :OptionalParam[String]  = OptDefault,
id_in :OptionalParam[js.Array[String]]  = OptDefault,
id_not_in :OptionalParam[js.Array[String]]  = OptDefault,
id_lt :OptionalParam[String]  = OptDefault,
id_lte :OptionalParam[String]  = OptDefault,
id_gt :OptionalParam[String]  = OptDefault,
id_gte :OptionalParam[String]  = OptDefault,
id_contains :OptionalParam[String]  = OptDefault,
id_not_contains :OptionalParam[String]  = OptDefault,
id_starts_with :OptionalParam[String]  = OptDefault,
id_not_starts_with :OptionalParam[String]  = OptDefault,
id_ends_with :OptionalParam[String]  = OptDefault,
id_not_ends_with :OptionalParam[String]  = OptDefault,
imageUrl :OptionalParam[String]  = OptDefault,
imageUrl_not :OptionalParam[String]  = OptDefault,
imageUrl_in :OptionalParam[js.Array[String]]  = OptDefault,
imageUrl_not_in :OptionalParam[js.Array[String]]  = OptDefault,
imageUrl_lt :OptionalParam[String]  = OptDefault,
imageUrl_lte :OptionalParam[String]  = OptDefault,
imageUrl_gt :OptionalParam[String]  = OptDefault,
imageUrl_gte :OptionalParam[String]  = OptDefault,
imageUrl_contains :OptionalParam[String]  = OptDefault,
imageUrl_not_contains :OptionalParam[String]  = OptDefault,
imageUrl_starts_with :OptionalParam[String]  = OptDefault,
imageUrl_not_starts_with :OptionalParam[String]  = OptDefault,
imageUrl_ends_with :OptionalParam[String]  = OptDefault,
imageUrl_not_ends_with :OptionalParam[String]  = OptDefault,
updatedAt :OptionalParam[String]  = OptDefault,
updatedAt_not :OptionalParam[String]  = OptDefault,
updatedAt_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_lt :OptionalParam[String]  = OptDefault,
updatedAt_lte :OptionalParam[String]  = OptDefault,
updatedAt_gt :OptionalParam[String]  = OptDefault,
updatedAt_gte :OptionalParam[String]  = OptDefault):PostFilter = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[PostFilter]
 }

}

     


@js.native
trait PostOrderBy extends js.Object

object PostOrderBy {
  @inline def createdAt_ASC = "createdAt_ASC".asInstanceOf[PostOrderBy] 
@inline def createdAt_DESC = "createdAt_DESC".asInstanceOf[PostOrderBy] 
@inline def description_ASC = "description_ASC".asInstanceOf[PostOrderBy] 
@inline def description_DESC = "description_DESC".asInstanceOf[PostOrderBy] 
@inline def id_ASC = "id_ASC".asInstanceOf[PostOrderBy] 
@inline def id_DESC = "id_DESC".asInstanceOf[PostOrderBy] 
@inline def imageUrl_ASC = "imageUrl_ASC".asInstanceOf[PostOrderBy] 
@inline def imageUrl_DESC = "imageUrl_DESC".asInstanceOf[PostOrderBy] 
@inline def updatedAt_ASC = "updatedAt_ASC".asInstanceOf[PostOrderBy] 
@inline def updatedAt_DESC = "updatedAt_DESC".asInstanceOf[PostOrderBy] 
}

     


@js.native
trait Query extends js.Object  {
  val viewer :Viewer = js.native
val node :js.UndefOr[Node] = js.native
}
     



trait SignupUserInput extends js.Object  {
  val clientMutationId :String 
}

object SignupUserInput {

 def apply(clientMutationId :String ):SignupUserInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[SignupUserInput]
 }

}

     



trait UpdateFile extends js.Object  {
  val id :String 
val name :js.UndefOr[String]  = js.undefined
}

object UpdateFile {

 def apply(id :String ,
name :OptionalParam[String]  = OptDefault):UpdateFile = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateFile]
 }

}

     



trait UpdateFileInput extends js.Object  {
  val id :String 
val name :js.UndefOr[String]  = js.undefined
val clientMutationId :String 
}

object UpdateFileInput {

 def apply(id :String ,
name :OptionalParam[String]  = OptDefault,
clientMutationId :String ):UpdateFileInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateFileInput]
 }

}

     


@js.native
trait UpdateFilePayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val file :js.UndefOr[File] = js.native
val edge :js.UndefOr[FileEdge] = js.native
}
     



trait UpdateOrCreateFileInput extends js.Object  {
  val update :UpdateFile 
val create :CreateFile 
val clientMutationId :String 
}

object UpdateOrCreateFileInput {

 def apply(update :UpdateFile ,
create :CreateFile ,
clientMutationId :String ):UpdateOrCreateFileInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateOrCreateFileInput]
 }

}

     


@js.native
trait UpdateOrCreateFilePayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val file :js.UndefOr[File] = js.native
val edge :js.UndefOr[FileEdge] = js.native
}
     



trait UpdateOrCreatePostInput extends js.Object  {
  val update :UpdatePost 
val create :CreatePost 
val clientMutationId :String 
}

object UpdateOrCreatePostInput {

 def apply(update :UpdatePost ,
create :CreatePost ,
clientMutationId :String ):UpdateOrCreatePostInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateOrCreatePostInput]
 }

}

     


@js.native
trait UpdateOrCreatePostPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val post :js.UndefOr[Post] = js.native
val edge :js.UndefOr[PostEdge] = js.native
}
     



trait UpdateOrCreateUserInput extends js.Object  {
  val update :UpdateUser 
val clientMutationId :String 
}

object UpdateOrCreateUserInput {

 def apply(update :UpdateUser ,
clientMutationId :String ):UpdateOrCreateUserInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateOrCreateUserInput]
 }

}

     


@js.native
trait UpdateOrCreateUserPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val user :js.UndefOr[User] = js.native
val edge :js.UndefOr[UserEdge] = js.native
}
     



trait UpdatePost extends js.Object  {
  val description :js.UndefOr[String]  = js.undefined
val id :String 
val imageUrl :js.UndefOr[String]  = js.undefined
}

object UpdatePost {

 def apply(description :OptionalParam[String]  = OptDefault,
id :String ,
imageUrl :OptionalParam[String]  = OptDefault):UpdatePost = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdatePost]
 }

}

     



trait UpdatePostInput extends js.Object  {
  val description :js.UndefOr[String]  = js.undefined
val id :String 
val imageUrl :js.UndefOr[String]  = js.undefined
val clientMutationId :String 
}

object UpdatePostInput {

 def apply(description :OptionalParam[String]  = OptDefault,
id :String ,
imageUrl :OptionalParam[String]  = OptDefault,
clientMutationId :String ):UpdatePostInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdatePostInput]
 }

}

     


@js.native
trait UpdatePostPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val post :js.UndefOr[Post] = js.native
val edge :js.UndefOr[PostEdge] = js.native
}
     



trait UpdateUser extends js.Object  {
  val id :String 
}

object UpdateUser {

 def apply(id :String ):UpdateUser = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateUser]
 }

}

     



trait UpdateUserInput extends js.Object  {
  val id :String 
val clientMutationId :String 
}

object UpdateUserInput {

 def apply(id :String ,
clientMutationId :String ):UpdateUserInput = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UpdateUserInput]
 }

}

     


@js.native
trait UpdateUserPayload extends js.Object  {
  val viewer :Viewer = js.native
val clientMutationId :String = js.native
val user :js.UndefOr[User] = js.native
val edge :js.UndefOr[UserEdge] = js.native
}
     


@js.native
trait User extends Node  {
  val createdAt :String = js.native

val updatedAt :String = js.native
}
     


@js.native
trait UserConnection extends js.Object  {
  val pageInfo :PageInfo = js.native
val edges :js.Array[UserEdge] = js.native
val count :Int = js.native
}
     


@js.native
trait UserEdge extends js.Object  {
  val node :User = js.native
val cursor :String = js.native
}
     



trait UserFilter extends js.Object  {
  val AND :js.UndefOr[js.Array[UserFilter]]  = js.undefined
val OR :js.UndefOr[js.Array[UserFilter]]  = js.undefined
val createdAt :js.UndefOr[String]  = js.undefined
val createdAt_not :js.UndefOr[String]  = js.undefined
val createdAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val createdAt_lt :js.UndefOr[String]  = js.undefined
val createdAt_lte :js.UndefOr[String]  = js.undefined
val createdAt_gt :js.UndefOr[String]  = js.undefined
val createdAt_gte :js.UndefOr[String]  = js.undefined
val id :js.UndefOr[String]  = js.undefined
val id_not :js.UndefOr[String]  = js.undefined
val id_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val id_lt :js.UndefOr[String]  = js.undefined
val id_lte :js.UndefOr[String]  = js.undefined
val id_gt :js.UndefOr[String]  = js.undefined
val id_gte :js.UndefOr[String]  = js.undefined
val id_contains :js.UndefOr[String]  = js.undefined
val id_not_contains :js.UndefOr[String]  = js.undefined
val id_starts_with :js.UndefOr[String]  = js.undefined
val id_not_starts_with :js.UndefOr[String]  = js.undefined
val id_ends_with :js.UndefOr[String]  = js.undefined
val id_not_ends_with :js.UndefOr[String]  = js.undefined
val updatedAt :js.UndefOr[String]  = js.undefined
val updatedAt_not :js.UndefOr[String]  = js.undefined
val updatedAt_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_not_in :js.UndefOr[js.Array[String]]  = js.undefined
val updatedAt_lt :js.UndefOr[String]  = js.undefined
val updatedAt_lte :js.UndefOr[String]  = js.undefined
val updatedAt_gt :js.UndefOr[String]  = js.undefined
val updatedAt_gte :js.UndefOr[String]  = js.undefined
}

object UserFilter {

 def apply(AND :OptionalParam[js.Array[UserFilter]]  = OptDefault,
OR :OptionalParam[js.Array[UserFilter]]  = OptDefault,
createdAt :OptionalParam[String]  = OptDefault,
createdAt_not :OptionalParam[String]  = OptDefault,
createdAt_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
createdAt_lt :OptionalParam[String]  = OptDefault,
createdAt_lte :OptionalParam[String]  = OptDefault,
createdAt_gt :OptionalParam[String]  = OptDefault,
createdAt_gte :OptionalParam[String]  = OptDefault,
id :OptionalParam[String]  = OptDefault,
id_not :OptionalParam[String]  = OptDefault,
id_in :OptionalParam[js.Array[String]]  = OptDefault,
id_not_in :OptionalParam[js.Array[String]]  = OptDefault,
id_lt :OptionalParam[String]  = OptDefault,
id_lte :OptionalParam[String]  = OptDefault,
id_gt :OptionalParam[String]  = OptDefault,
id_gte :OptionalParam[String]  = OptDefault,
id_contains :OptionalParam[String]  = OptDefault,
id_not_contains :OptionalParam[String]  = OptDefault,
id_starts_with :OptionalParam[String]  = OptDefault,
id_not_starts_with :OptionalParam[String]  = OptDefault,
id_ends_with :OptionalParam[String]  = OptDefault,
id_not_ends_with :OptionalParam[String]  = OptDefault,
updatedAt :OptionalParam[String]  = OptDefault,
updatedAt_not :OptionalParam[String]  = OptDefault,
updatedAt_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_not_in :OptionalParam[js.Array[String]]  = OptDefault,
updatedAt_lt :OptionalParam[String]  = OptDefault,
updatedAt_lte :OptionalParam[String]  = OptDefault,
updatedAt_gt :OptionalParam[String]  = OptDefault,
updatedAt_gte :OptionalParam[String]  = OptDefault):UserFilter = {

   val p = FunctionObjectMacro()
   p.asInstanceOf[UserFilter]
 }

}

     


@js.native
trait UserOrderBy extends js.Object

object UserOrderBy {
  @inline def createdAt_ASC = "createdAt_ASC".asInstanceOf[UserOrderBy] 
@inline def createdAt_DESC = "createdAt_DESC".asInstanceOf[UserOrderBy] 
@inline def id_ASC = "id_ASC".asInstanceOf[UserOrderBy] 
@inline def id_DESC = "id_DESC".asInstanceOf[UserOrderBy] 
@inline def updatedAt_ASC = "updatedAt_ASC".asInstanceOf[UserOrderBy] 
@inline def updatedAt_DESC = "updatedAt_DESC".asInstanceOf[UserOrderBy] 
}

     


@js.native
trait Viewer extends js.Object  {
  val allFiles :FileConnection = js.native
val allPosts :PostConnection = js.native
val allUsers :UserConnection = js.native
val user :js.UndefOr[User] = js.native
val File :js.UndefOr[File] = js.native
val Post :js.UndefOr[Post] = js.native
val User :js.UndefOr[User] = js.native
val id :String = js.native
}
     

       